name: Format sources list

on:
  pull_request:
    paths:
      - 'sources.txt'
      - 'sourcesnsfw.txt'
  workflow_dispatch:

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check if sources.txt is sorted and unique
        run: |
          if ! diff sources.txt <(LC_ALL=C sort -u sources.txt); then
            echo "Error: sources.txt is not sorted or contains duplicates."
            exit 1
          fi
